theme = "nord"

[editor]
true-color = true
line-number = "relative"
cursorline = true

[editor.file-picker]
hidden = false
[editor.auto-save]
focus-lost=true
after-delay.enable=true

[editor.lsp]
display-inlay-hints = true
enable=true
auto-signature-help=true
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-modification-indicator", "read-only-indicator"]
center = ["file-name"]
right = ["diagnostics", "register", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "â”‚"
mode.normal = "LOCKED"
mode.insert = "WORKING"
mode.select = "VISUAL SEL"
